### ISSUE TITLE
Arrange JavaScript Embedding Code

### ISSUE THREAD

**Issue by sendz** [Dirakit/Dirakit-Admin#1]
@fauzan-ngantuk first rule of embedding JS code

- Load first major framework such as jquery
- Then load JS for component such as JS code for UI
- Load custom or own code JS last

So, it will

1. jQuery
2. semantic
3. another JS plugin
4. custom.js

**Comment by nauzaf** [comment]
Okok

**Comment by nauzaf** [comment]
@sendz udah bener blm ?

**Comment by nauzaf** [comment]
commit yg sebelume ada bug .. sekarang udah bener blm mas ? @sendz

**Comment by sendz** [comment]
@fauzan-ngantuk copas id commit nya ke sini

**Comment by sendz** [comment]
@fauzan-ngantuk udah bener, sekarang pindahin semua embed `js` ke sebelum `</body>`

**Comment by nauzaf** [comment]
ini commit yg bug  : d351356b8edf28a9ffc4311672d95f4726cfff2c @sendz

**Comment by nauzaf** [comment]
@sendz ini ding haha salah copy 450926798327c6e697cdfa7f2416ba4ca06b1375

**Comment by nauzaf** [comment]
updated -----> c010d2981d41db918dffcf4dd3b56af17dc4916c

**Comment by nauzaf** [comment]
udah bisa aku close ?
