### ISSUE TITLE
Page looks too small on retina display.

### ISSUE THREAD

**Issue by sendz** [Dirakit/Dirakit-Admin#2]
Please add `<meta name="viewport" content="width=device-width, initial-scale=1">` inside `<head></head>` tag.

**Comment by nauzaf** [comment]
430bc841fd4fa1894c02fb50c13fd74bd308998d

**Comment by nauzaf** [comment]
@sendz 430bc841fd4fa1894c02fb50c13fd74bd308998d done ya

**Comment by sendz** [comment]
@fauzan-ngantuk gak done kalau belum PR
