### ISSUE TITLE
Add Notification and Unread Message count on top of the icon.

### ISSUE THREAD

**Issue by sendz** [Dirakit/Dirakit-Admin#3]
Reference: [Semantic Floating Label](http://semantic-ui.com/elements/label.html#floating)

**Comment by nauzaf** [comment]
@sendz aku udah PR, commit ---> 7e0be7805f5dfdca3e945d7ce7fde8f7b8c6868b

**Comment by nauzaf** [comment]
@sendz udah aku fix , bener nggak ? ---> 5c5948f81f99f4e4e79a4a814c56276745368136

**Comment by sendz** [comment]
@fauzan-ngantuk masih salah 🔢

**Comment by nauzaf** [comment]
@sendz udah bener belum mas ? fc800e85f02ae51f41fa7ace6372d8c671cefe8f

**Comment by nauzaf** [comment]
@sendz udah bisa di close blm mas ? soalnya issue nya kan ttg notifikasi feature
